name: CI

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amaccis/node-libstemmer:1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm run install
      - name: Run tests
        run: npm run test
