name: CI

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        container:
          #- "amaccis/node-libstemmer:20.18.2-2.2.0"
          #- "amaccis/node-libstemmer:22.13.1-2.2.0"
          - "amaccis/node-libstemmer:20-2.2.0"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
